# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[install]
# Use the fastest install strategy (symlinks)
strategy = "clone"

[test]
# Enable TypeScript by default
tsconfig = "tsconfig.json"

[dev]
# Auto-install dependencies when running bun run
autoinstall = true

[bundle]
# Enable bundling
minify = true
splitting = true

[define]
# Define global constants
# Example: VERSION = "1.0.0"

[debug]
# Enable debug logging
# loglevel = "debug"
